openapi: 3.0.3
info:
  title: Immunity IAST API
  version: 1.0.0
  description: Immunity IAST REST API.
paths:
  /api/agent/health:
    get:
      operationId: agent_health_retrieve
      description: Healthcheck
      tags:
      - agent
      security:
      - tokenAuth: []
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
