version: '3'

services:
  db:
    image: postgres:12-alpine
    container_name: postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    restart: always
    networks:
      - opendisknet
    healthcheck:
      test: pg_isready -U postgres
      interval: 20s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.0.15
    container_name: redis-master
    command: redis-server --save 20 1 --loglevel warning
    expose:
      - "6379"
    volumes:
      - redis-master-data:/data
    restart: always
    networks:
      - opendisknet
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 5

  redis-slave:
    image: redis:7.0.15
    depends_on:
      - redis
    command: >
      sh -c "redis-server --slaveof redis-master 6379 --save 20 1 --loglevel warning"
    expose:
      - "6379"
    volumes:
      - redis-slave-data:/data
    restart: always
    networks:
      - opendisknet
    healthcheck:
      test: redis-cli -h redis-slave ping
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    image: opendisk-api:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile
    shm_size: 1g
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    environment:
      - SECRET_KEY=Sx5SE_rtqnau0VxhW!Zx&r%$*d+uy6lum5J&6GpwrOXwefEWf
      - API_URL=127.0.0.1
      - API_PORT=80
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    depends_on:
      - db
    restart: always
    networks:
      - opendisknet
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 20s
      timeout: 5s
      retries: 3

  worker:
    image: opendisk-worker:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile.worker
    shm_size: 1g
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    environment:
      - SECRET_KEY=Sx5SE_rtqnau0VxhW!Zx&r%$*d+uy6lum5J&6GpwrOXwefEWf
      - API_URL=127.0.0.1
      - API_PORT=80
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    depends_on:
      - db
      - api
      - redis
    restart: always
    networks:
      - opendisknet
    healthcheck:
      test: celery -A core status | grep 'celery@'
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: opendisk-nginx:latest
    build: ./nginx/
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - api
      - worker
    restart: always
    networks:
      - opendisknet
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 20s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis-master-data:
  redis-slave-data:

networks:
  opendisknet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"
