version: '2'

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
    networks:
      - immunitynet
    healthcheck:
      test: pg_isready -U postgres
      interval: 20s
      timeout: 5s
      retries: 3

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-master
    command: redis-server --save 20 1 --loglevel warning
    expose:
      - 6379
    volumes:
      - redis-master-data:/data
    restart: always
    networks:
      - immunitynet
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 5

  redis-slave:
    image: redis:${REDIS_VERSION}
    depends_on:
      - redis
    command: >
      sh -c "redis-server --slaveof redis-master 6379 --save 20 1 --loglevel warning"
    expose:
      - 6379
    volumes:
      - redis-slave-data:/data
    restart: always
    networks:
      - immunitynet
    healthcheck:
      test: redis-cli -h redis-slave ping
      interval: 30s
      timeout: 10s
      retries: 5

  immunity:
    image: l1ghth4t/immunity-iast:latest
    shm_size: 1g
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    environment:
      - API_HOST
      - API_PORT
      - POSTGRES_PORT
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - db
    restart: always
    networks:
      - immunitynet
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 20s
      timeout: 5s
      retries: 3

  worker:
    image: l1ghth4t/immunity-iast-worker:latest
    shm_size: 1g
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    environment:
      - API_HOST
      - API_PORT
      - POSTGRES_PORT
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    depends_on:
      - db
      - immunity
      - redis
    restart: always
    networks:
      - immunitynet
    healthcheck:
      test: celery -A core status | grep 'celery@'
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: l1ghth4t/immunity-iast-nginx:latest
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - immunity
      - worker
    restart: always
    networks:
      - immunitynet

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis-master-data:
  redis-slave-data:

networks:
  immunitynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/16"
