# Generated by Django 5.1.3 on 2024-11-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Приложение",
                "verbose_name_plural": "Приложения",
            },
        ),
        migrations.AlterModelOptions(
            name="context",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Контекст выполнения",
                "verbose_name_plural": "Контексты выполнения",
            },
        ),
        migrations.AlterModelOptions(
            name="dataset",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Датасет",
                "verbose_name_plural": "Датасеты",
            },
        ),
        migrations.AlterModelOptions(
            name="datasetlabel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Метка датасета",
                "verbose_name_plural": "Метки датасетов",
            },
        ),
        migrations.AddField(
            model_name="datasetlabel",
            name="dataset",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dataset",
            ),
            preserve_default=False,
        ),
    ]
