name: Validate nginx config

on:
  pull_request:
    branches:
      - 'master'

jobs:
  install_nginx_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx

      - name: Test Nginx Configuration
        run: sudo nginx -t
