name: Dockle Linting

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'master'

jobs:
  dockle-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./docker/Dockerfile
          push: false
          tags: immunity_iast:${{ github.sha }}

      - name: Run Dockle on Dockerfile
        uses: goodwithtech/dockle-action@main
        with:
          image: immunity_iast:${{ github.sha }}
          format: json
          exit-code: 1
          exit-level: error
          output: dockle-report.json
