name: Eslint

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        cd frontend
        npm install
    - name: Lint
      run: |
        cd frontend
        npm run lint
    - name: Audit
      run: |
        cd frontend
        npm audit
    - name: Try to build
      run: |
        cd frontend
        npm run build
