name: Hadolint

on:
  pull_request:
    branches:
      - 'master'

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Main Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "docker/Dockerfile"
          ignored: DL3008
